general.live_config_reload = true

general.import = [
   #"~/.config/alacritty/catppuccin-latte.toml"
   # "~/.config/alacritty/catppuccin-frappe.toml"
   #"~/.config/alacritty/themes/catppuccin-macchiato.toml",
   #"~/.config/alacritty/catppuccin-mocha.toml"
   "~/.config/alacritty/themes/gruvbox2.toml"
   #"~/.config/alacritty/alacritty-colors.toml"
   #"~/.config/alacritty/themes/kanagawa_dragon.toml"
   #"~/.config/alacritty/themes/kanagawa_wave.toml"
   #"~/.config/alacritty/themes/rose-pine-dawn.toml"
   #"~/.config/alacritty/themes/rose-pine.toml"
]

[env]
TERM = "alacritty"

[font]
size = 16

[font.normal]
# Custom patch of the Zed font: https://mutsuntsai.github.io/fontfreeze/
family = "Zed Plex Mono"
style = "Regular"

[scrolling]
history = 10000

[window]
dynamic_title = false
title = "Terminal"
decorations = "Buttonless"
dynamic_padding = true
opacity = 1

[mouse]
hide_when_typing = true
