---@type table<string, table<string, boolean>>

return {
	["goolord/alpha-nvim"] = { enabled = true, start = true },
	["windwp/nvim-autopairs"] = { enabled = true, start = true },
	["hrsh7th/nvim-cmp"] = { enabled = true, start = true },
	["stevearc/conform.nvim"] = { enabled = true, start = true },
	["windwp/nvim-ts-autotag"] = { enabled = true, start = true },
	["catppuccin/nvim"] = { enabled = false, start = false },
	["f-person/git-blame.nvim"] = { enabled = true, start = true },
	["ellisonleao/gruvbox.nvim"] = { enabled = true, start = true },
	["NMAC427/guess-indent.nvim"] = { enabled = true, start = true },
	["rebelot/kanagawa.nvim"] = { enabled = true, start = true },
	["neovim/nvim-lspconfig"] = { enabled = true, start = true },
	["nvim-lualine/lualine.nvim"] = { enabled = true, start = true },
	["echasnovski/mini.nvim"] = { enabled = true, start = true },
	["alexghergh/nvim-tmux-navigation"] = { enabled = true, start = true },
	["stevearc/oil.nvim"] = { enabled = true, start = true },
	["nvim-telescope/telescope.nvim"] = { enabled = true, start = true },
	["kylechui/nvim-surround"] = { enabled = true, start = true },
	["folke/todo-comments.nvim"] = { enabled = true, start = true },
	["nvim-treesitter/nvim-treesitter"] = { enabled = true, start = true },
	["ckolkey/ts-node-action"] = { enabled = true, start = true },
	["pmizio/typescript-tools.nvim"] = { enabled = true, start = true },
	["debugloop/telescope-undo.nvim"] = { enabled = true, start = true },
	["folke/which-key.nvim"] = { enabled = true, start = true },
	["echasnovski/mini.base16"] = { enabled = false, start = false },
	["nvim-tree/nvim-tree.lua"] = { enabled = false, start = false },
	["saghen/blink.cmp"] = { enabled = false, start = false },
	["rose-pine"] = { enabled = true, start = true },
}
