
[colors.primary]
background = "#1d2021"
foreground = "#d5c4a1"

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = "#1d2021"
cursor = "#d5c4a1"

# Normal colors
[colors.normal]
black    = "#1d2021"
red      = "#fb4934"
green    = "#b8bb26"
yellow   = "#fabd2f"
blue     = "#83a598"
magenta  = "#d3869b"
cyan     = "#8ec07c"
white    = "#d5c4a1"

# Bright colors
[colors.bright]
black    = "#665c54"
red      = "#fe8019"
green    = "#3c3836"
yellow   = "#504945"
blue     = "#bdae93"
magenta  = "#ebdbb2"
cyan     = "#d65d0e"
white    = "#fbf1c7"
